version: '3'
services:
  mysqldb:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=docker-machine env
      - MYSQL_USER=DB_USER
      - MYSQL_PASSWORD=DB_PASS
